### ISSUE TITLE
Failed to run custom build command for `openblas-src v0.7.0`

### ISSUE THREAD

**Issue by ToriTyler** [blas-lapack-rs/openblas-src#29]
Hi everyone,

I am using ```ndarray-linalg``` and therefore need link to a backend crate, so I'm using ```openblas```.

What I did are:

1. Install ```gfortran``` and ```libopenblas-dev``` via ```sudo apt-get ```.
2. Add following dependencies to my ```Cargo.toml``` file:
```
ndarray = "0.12"
ndarray-linalg = "0.11.0"
openblas-src="0.7"
```
3. Add:
```
extern crate openblas_src;
```
to my ```lib.rs```

But when I did ```cargo run```, the following error message showed up:
```
ranlib ../../../libopenblas_nehalemp-r0.3.4.a
make[3]: Leaving directory '/home/tori/.cargo/registry/src/github.com-1ecc6299db9ec823/openblas-src-0.7.0/source_x86_64-unknown-linux-gnu/lapack-netlib/LAPACKE/utils'
make[2]: Leaving directory '/home/tori/.cargo/registry/src/github.com-1ecc6299db9ec823/openblas-src-0.7.0/source_x86_64-unknown-linux-gnu/lapack-netlib/LAPACKE'
make[1]: Leaving directory '/home/tori/.cargo/registry/src/github.com-1ecc6299db9ec823/openblas-src-0.7.0/source_x86_64-unknown-linux-gnu/lapack-netlib'
make[1]: Entering directory '/home/tori/.cargo/registry/src/github.com-1ecc6299db9ec823/openblas-src-0.7.0/source_x86_64-unknown-linux-gnu/exports'
cc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.4\" -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_nehalemp-r0.3.4.so \
-Wl,--whole-archive ../libopenblas_nehalemp-r0.3.4.a -Wl,--no-whole-archive \
-Wl,-soname,libopenblas.so.0 -lm -lpthread -lgfortran -lm -lpthread -lgfortran
cc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.4\" -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -w -o linktest linktest.c ../libopenblas_nehalemp-r0.3.4.so -L/home/tori/miniconda3/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L. -L/home/tori/miniconda3/lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../..  -lgfortran -lm -lquadmath -lm -lc   && echo OK.

Makefile:145: recipe for target '../libopenblas_nehalemp-r0.3.4.so' failed
make[1]: Leaving directory '/home/tori/.cargo/registry/src/github.com-1ecc6299db9ec823/openblas-src-0.7.0/source_x86_64-unknown-linux-gnu/exports'
Makefile:101: recipe for target 'shared' failed

--- stderr
make[1]: warning: -jN forced in submake: disabling jobserver mode.
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: warning: -jN forced in submake: disabling jobserver mode.
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: warning: -jN forced in submake: disabling jobserver mode.
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: warning: -jN forced in submake: disabling jobserver mode.
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: warning: -jN forced in submake: disabling jobserver mode.
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: warning: -jN forced in submake: disabling jobserver mode.
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: warning: -jN forced in submake: disabling jobserver mode.
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: warning: -jN forced in submake: disabling jobserver mode.
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: warning: -jN forced in submake: disabling jobserver mode.
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: warning: -jN forced in submake: disabling jobserver mode.
../libopenblas_nehalemp-r0.3.4.so: undefined reference to `xerbla'
collect2: error: ld returned 1 exit status
make[1]: *** [../libopenblas_nehalemp-r0.3.4.so] Error 1
make: *** [shared] Error 2
thread 'main' panicked at 'Failed: `"make" "libs" "netlib" "shared" "BINARY=64" "YES_CBLAS=1" "YES_LAPACKE=1" "-j4"` (exit code: 2)', /home/tori/.cargo/registry/src/github.com-1ecc6299db9ec823/openblas-src-0.7.0/build.rs:68:17
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: build_script_build::run
             at ./build.rs:68
   8: build_script_build::main
             at ./build.rs:49
   9: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  10: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  11: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  12: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  13: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  14: main
  15: __libc_start_main
  16: _start
```
I'm totally confused.... Please help me!

Thanks,
Tori

**Comment by IvanUkhov** [comment]
Hi, perhaps it has something to do with two versions of OpenBLAS. One is installed by you, and one is compiled internally in this package. Try without yours, or use the `system` feature here.
